# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

addons:
  apt:
    packages:
      - gdal-bin
      - proj-bin
      - libgdal-dev
      - libgdal1-dev
      - libproj-dev
      - libgeos-dev

os:
  - osx


matrix:
allow_failures:
    - os: osx


env:
  global:
    - R_BUILD_ARGS=" --no-build-vignettes --no-manual "
    - R_CHECK_ARGS=" --timings --as-cran --no-manual --no-vignettes --install-args=--build"


r_packages:
  - covr
  - devtools

after_success:
  - Rscript -e 'library(covr); codecov()'
