# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

addons:
  apt:
    packages:
      - gdal-bin
      - proj-bin
      - libgdal1-dev
      - libproj-dev
      - libgeos-dev
