# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

addons:
  apt:
    packages:
      - gdal-bin
      - proj-bin
      - libgdal-dev
      - libgdal1-dev
      - libproj-dev
      - libgeos-dev

os:
  - linux
  - osx
  - windows


matrix:
allow_failures:
    - os: linus
    - os: osx
    - os: windows

    
env:
  global:
    - R_BUILD_ARGS=" --no-build-vignettes --no-manual "
    - R_CHECK_ARGS=" --timings --as-cran --no-manual --no-vignettes --install-args=--build"
