---
title: "The crestr community"
author: "Manuel Chevalier"
date: "`r Sys.Date()`"
output:
    rmarkdown::html_vignette:
        self_contained: no
vignette: >
  %\VignetteIndexEntry{The crestr community}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```



## Join the mailing-list

As the crest community has been rapidly growing since the release of the _crestr_ package and associated publication last year, I created a mailing list of crest-interested users to share information more efficiently. Controlled and limited communication through this channel are guaranteed since we all receive too many emails already.  To join the mailing list, you only need to enter your name and contact below (feel free to share this link with your colleagues and students who may be interested). Emails will include the following information:

- Early notifications of upcoming workshops to allow you to secure spots (independent online events or associated with international congresses);
- Publication highlights of studies involving crest (please send me your publication(s) if you want your work advertised here!);
- Notifications about important updates of the crestr R package (bug fixing, new features, new vignettes, etc.);
- Communications from crest/r members relevant to this community.



<br >

<form action="https://formspree.io/f/xdovbpaw" method="POST" >
    First name: <input type="text" name="First name" placehold="Your name">
    Last name: <input type="text" name="Last name" placehold="Your name">
    Email: <input type="email" name="_replyto" placeholder="Your email">
    <input type="submit" value="Send">
    <input type="hidden" name="_subject" value="New member crest/r mailing list" />
</form>

<br >


## crestr workshops

Since 2022, I started to organise hands-on training workshops for _crestr_. Generally, the workshop is divided in four parts:
1.	I introduce the conceptuals and mathematical bases of the method and discuss the different assumptions necessary to model the datasets. This is followed by a short Q&A session.
2.	I then describe the architecture of the package and the structure of a crest analysis.
3.	I then showcase the use of the pacjage with an example dataset. The part is interactive and allows the the participants to connect the different functionalities of the package with the theoretical elements presented during Part 1.
4.	Finally, the participants are given the opportunity to start using the package with their own data, or an example dataset I provide.

**Target audience**: Colleagues and ECRs who produce and/or use palaeoecological datasets to understand past climate change.

**Required skills**: understanding the nature and limitations of palaeoecological datasets, such as pollen data. Beginner notions of R (nothing fancy).


> **_NOTE:_**  If you are organising an event, big or small, and would be interested in hosting a _crestr_ workshop, do not hesitate to contact me at <paleo@manuelchevalier.com> to discuss opportunities.


The slides, data and scripts used at previous crestr workshops are accessible here:
* GEOTOP Montreal, Canada, March 2024 (crestr v1.3.x): [[slides]](https://github.com/mchevalier2/mchevalier2.github.io/blob/94628034c5ba32d49cce3aeca20de4bb57b965ac/assets/openscience/workshops/Crestr-Montreal-2024.pdf)
* INQUA Rome, Italy, July 2023 (crestr v1.3.x): [[slides]](https://github.com/mchevalier2/mchevalier2.github.io/blob/94628034c5ba32d49cce3aeca20de4bb57b965ac/assets/openscience/workshops/Crestr-INQUA2023.pdf) [[data & script]](https://github.com/mchevalier2/mchevalier2.github.io/blob/94628034c5ba32d49cce3aeca20de4bb57b965ac/assets/openscience/workshops/Crestr-INQUA2023-material.zip)
* IPA-IAL Bariloche, Argentina, December 2022 (crestr v1.2.x): [[slides]](https://github.com/mchevalier2/mchevalier2.github.io/blob/94628034c5ba32d49cce3aeca20de4bb57b965ac/assets/openscience/workshops/Crestr-IAL-IPA-2022.pdf)
* SASQUA St-Lucia, South Africa, September 2022 (crestr v1.2.x): [[slides]](https://github.com/mchevalier2/mchevalier2.github.io/blob/94628034c5ba32d49cce3aeca20de4bb57b965ac/assets/openscience/workshops/Crestr-SASQUA-2022.pdf)
