#' Displays the log of the proxy-species association
#'
#' Displays the log of the proxy-species association performed by the
#' crest.get_modern_data() or crest.set_modern_data()
#'
#' @param x A \code{\link{crestObj}} generated by one of the following functions:
#'        \code{\link{crest.get_modern_data}}, \code{\link{crest.set_modern_data}},
#'        \code{\link{crest.calibrate}}, \code{\link{crest.reconstruct}},
#'        \code{\link{loo}}, or \code{\link{crest}} functions.
#' @export
#' @examples
#'
#' PSE_log(reconstr)
#'
PSE_log <- function(x) {
    if(base::missing(x)) x

    if(!is.crestObj(x)) {
        cat('\nx should be a crestObj.\n\n')
        return(invisible(NA))
    }
    print(x$misc$taxa_notes)
    invisible()
}
