#' Export the results
#'
#' Export the results generated by the reconstruction
#'
#' @inheritParams crestObj
#' @param sitename The name of the site (default: x$misc$site_info$sitename)
#' @param climate The climate data to export.
#' @param loc The path where to export the data (default: working directory)
#' @param as.csv Boolean to indicate if the data should be exported as csv (TRUE) or xlsx (FALSE, default)
#' @param fullPosterior A boolean to export the climate posterior probability (default FALSE)
#' @param loo A boolean to export the leave-one-out data if they exist (default FALSE)
#' @param weights A boolean to export the weights derived from the percentages (default FALSE)
#' @param pdfs A boolean to export the taxa's pdfs (default FALSE)
#' @export
#' @examples
#' \dontrun{
#'   data(crest_ex)
#'   data(crest_ex_pse)
#'   data(crest_ex_selection)
#'   recons <- crest(
#'     df = crest_ex, pse = crest_ex_pse, taxaType = 0,
#'     site_info = c(7.5, 7.5),
#'     climate = c("bio1", "bio12"), bin_width = c(2, 20),
#'     shape = c("normal", "lognormal"),
#'     selectedTaxa = crest_ex_selection, dbname = "crest_example",
#'     leave_one_out = TRUE
#'   )
#'   export(recons, sitename='crest_example', fullPosterior=TRUE, weights=TRUE, loo=TRUE)
#' }
#'
export <- function( x, sitename = x$misc$site_info$sitename,
                    climate = x$parameters$climate,
                    loc = getwd(), as.csv = FALSE,
                    fullPosterior = FALSE,
                    loo = FALSE,
                    weights = FALSE,
                    pdfs = FALSE) {

    if (length(x$reconstructions) == 0) {
        cat("No reconstruction available for export.\n")
        return(invisible(x))
    }

    if(is.na(sitename)) sitename <- 'crest_outputs'
    base::dir.create(base::file.path(loc, sitename), showWarnings = FALSE)

    if ((!'loo' %in% names(x$reconstructions[[climate[1]]])) & loo) {
        loo <- FALSE
        cat("WARNING: Leave-one-out data not available. Look at loo() for more details.\n")
    }

    save2<-function(recon, ...) { save(recon, ...)}
    save2(x, file = base::file.path(loc, sitename, paste0(sitename, '.RData')))

    if (! 'openxlsx' %in% utils::installed.packages()[,"Package"]) {
        as.csv <- TRUE
        cat("To export the data as xlsx, this function requires the package 'openxlsx'. The data will be saved as csv.\n\n")
    }

    for (clim in climate) {
        if(!as.csv) {
            base::dir.create(base::file.path(loc, sitename, clim), showWarnings = FALSE)
            wb <- openxlsx::createWorkbook()
        }

        #openxlsx::addWorksheet(wb, "ReadMe")

        #openxlsx::addWorksheet(wb, "Config")


        df <- cbind(x$reconstructions[[clim]]$optima[, -3], x$reconstructions[[clim]]$uncertainties[, -1], stringsAsFactors=FALSE)
        if(as.csv) {
            write.csv(df, base::file.path(loc, sitename, clim, 'Reconstruction.csv'), row.names=FALSE, quote=FALSE, na='')
        } else {
            openxlsx::addWorksheet(wb, "Reconstruction")
            openxlsx::writeData(wb, sheet = "Reconstruction", x = df)
        }


        if (fullPosterior) {
            df <- cbind(t(x$reconstructions[[clim]]$posterior))
            colnames(df) <- c(clim, x$inputs$x)
            if(as.csv) {
                write.csv(df, base::file.path(loc, sitename, clim, 'fullPosterior.csv'), row.names=FALSE, quote=FALSE, na='')
            } else {
                openxlsx::addWorksheet(wb, "fullPosterior")
                openxlsx::writeData(wb, sheet = "fullPosterior", x = df)
            }
        }


        df <- cbind(x$inputs$x, x$inputs$df, stringsAsFactors=FALSE)
        colnames(df)[1] <- c(x$inputs$x.name)
        if(as.csv) {
            write.csv(df, base::file.path(loc, sitename, clim, 'taxa_percentage.csv'), row.names=FALSE, quote=FALSE, na='')
        } else {
            openxlsx::addWorksheet(wb, "taxa_percentage")
            openxlsx::writeData(wb, sheet = "taxa_percentage", x = df)
        }


        if (weights) {
            df <- cbind(x$inputs$x, x$modelling$weights, stringsAsFactors=FALSE)
            colnames(df)[1] <- c(x$inputs$x.name)
            if(as.csv) {
                write.csv(df, base::file.path(loc, sitename, clim, 'taxa_weights.csv'), row.names=FALSE, quote=FALSE, na='')
            } else {
                openxlsx::addWorksheet(wb, "taxa_weights")
                openxlsx::writeData(wb, sheet = "taxa_weights", x = df)
            }
        }


        if (weights) {
            df <- x$inputs$x
            for (tax in names(x$reconstructions[[clim]]$loo)) {
                if (unique(is.na(as.vector(x$reconstructions[[clim]]$loo[[tax]])))) {
                    df <- cbind(df, rep(NA, length(x$inputs$x)))
                } else {
                    df <- cbind(df, x$reconstructions[[clim]]$loo[[tax]][, 'optima'])
                }
            }
            colnames(df) <- c(x$inputs$x.name, names(x$reconstructions[[clim]]$loo))
            if(as.csv) {
                write.csv(df, base::file.path(loc, sitename, clim, 'leave_one_out.csv'), row.names=FALSE, quote=FALSE, na='')
            } else {
                openxlsx::addWorksheet(wb, "leave_one_out")
                openxlsx::writeData(wb, sheet = "leave_one_out", x = df)
            }
        }


        df <- data.frame(ProxyName = x$inputs$taxa.name,
                         Family = rep(NA, length(x$inputs$taxa.name)),
                         Genus = rep(NA, length(x$inputs$taxa.name)),
                         Species = rep(NA, length(x$inputs$taxa.name)),
                         Selected = rep('Yes', length(x$inputs$taxa.name)),
                         Comment = rep(NA, length(x$inputs$taxa.name)),
                         stringsAsFactors = FALSE)

        for (tax in x$inputs$taxa.name) {
            tmp <- x$inputs$pse[, 'ProxyName'] == tax
            if(sum(tmp) > 1) {
                row = df[df[, 'ProxyName'] == tax, ]
                for(i in 2:sum(tmp)) {
                    df <- rbind(df, row)
                }
            }
            df[df[, 'ProxyName'] == tax, 2] <- as.character(x$inputs$pse[x$inputs$pse[, 'ProxyName'] == tax, 2])
            df[df[, 'ProxyName'] == tax, 3] <- as.character(x$inputs$pse[x$inputs$pse[, 'ProxyName'] == tax, 3])
            df[df[, 'ProxyName'] == tax, 4] <- as.character(x$inputs$pse[x$inputs$pse[, 'ProxyName'] == tax, 4])
            if (x$input$selectedTaxa[tax, clim] == 0) {
                df[df[, 'ProxyName'] == tax, 5:6] <- rep(c('No', paste0('Not sensitive to ', clim)), each=sum(tmp))
            }
        }

        for(n in names(x$misc$taxa_notes)) {
            for(tax in x$misc$taxa_notes[[n]]) {
                if(tax %in% x$inputs$pse[, 'ProxyName']) {
                    df <- rbind(df,
                                c(tax,
                                  as.character(x$inputs$pse[x$inputs$pse[, 'ProxyName'] == tax, 2]),
                                  as.character(x$inputs$pse[x$inputs$pse[, 'ProxyName'] == tax, 3]),
                                  as.character(x$inputs$pse[x$inputs$pse[, 'ProxyName'] == tax, 4]),
                                  'No',
                                  n), stringsAsFactors=FALSE)
                } else {
                    df <- rbind(df, c(tax, NA, NA, NA, 'No', n), stringsAsFactors=FALSE)
                }
            }
        }

        df <- df[with(df, order(Selected, Comment, ProxyName)), ]
        if(as.csv) {
            write.csv(df, base::file.path(loc, sitename, clim, 'selectedTaxa.csv'), row.names=FALSE, quote=FALSE, na='')
        } else {
            openxlsx::addWorksheet(wb, "selectedTaxa")
            openxlsx::writeData(wb, sheet = "selectedTaxa", x = df)
        }

        if(!as.csv) openxlsx::saveWorkbook(wb, file.path(loc, sitename, clim, paste0(clim, '.xlsx')), overwrite = TRUE)
    }

    invisible(x)
}
