#' Calculates how many species compose the respose of each taxon.
#'
#' Calculates how many species compose the respose of each taxon.
#'
#' @param x A crestObj generated by the crest.reconstruct() or crest() functions.
#' @export

getSpeciesdiversity <- function(x) {
    div <- rep(0, length(x$inputs$taxa.name))
    names(div) <- x$inputs$taxa.name

    for(tax in x$inputs$taxa.name) {
        if(is.list(x$modelling$pdfs[[tax]][[1]])) {
           div[tax] <- length(x$modelling$pdfs[[tax]][[1]]$pdfsp)
        }
    }

    div <- sort(div)
    div
}
